version: '3.7'
services:
  db:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webprogramming
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
  web:
    depends_on:
      - db
    image: tomcat:9.0.65
    volumes:
      - ./ProgrammazioneWebMattiaBressanEsame.war:/usr/local/tomcat/webapps/ProgrammazioneWebMattiaBressanEsame.war
    ports:
      - '8080:8080'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webprogramming
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root